[package]
name = "bioshell"
version = "4.0.0-dev"
edition = "2021"
description = "Provides the BioShell 4.0 package"
homepage = "https://bioshell.pl"
license = "Apache-2.0"
keywords = ["bioshell"]

[workspace]
members = [
    "bioshell-numerical",
    "bioshell-ff",
    "bioshell-sim",
]

[dependencies]
bioshell-numerical = { path = "./bioshell-numerical" }
bioshell-ff = { path = "./bioshell-ff" }
bioshell-sim = { path = "./bioshell-sim" }
clap = { version = "3.1.18", features = ["derive"] }
rand = "0.8.5"

[[bin]]
name = "polymer"
path = "src/polymer.rs"

[[bin]]
name = "disks"
path = "src/disks.rs"

[[bin]]
name = "argon"
path = "src/argon.rs"