[package]
name = "bioshell"
version = "4.0.0-dev"
edition = "2021"
description = "Provides the BioShell 4.0 package"
homepage = "https://bioshell.pl"
license = "Apache-2.0"
keywords = ["bioshell"]

[workspace]
members = [
    "bioshell-core",
    "bioshell-numerical",
    "bioshell-ff",
    "bioshell-sim",
    "bioshell-statistics",
    "bioshell-clustering",
    "bioshell-montecarlo",
    "bioshell-cartesians"
]

[dependencies]
bioshell-core = { path = "./bioshell-core" }
bioshell-numerical = { path = "./bioshell-numerical" }
bioshell-ff = { path = "./bioshell-ff" }
bioshell-sim = { path = "./bioshell-sim" }
bioshell-clustering = { path = "./bioshell-clustering" }
bioshell-statistics = { path = "./bioshell-statistics" }
bioshell-montecarlo = { path = "./bioshell-montecarlo" }
bioshell-cartesians = { path = "./bioshell-cartesians" }

clap = { version = "3.1.18", features = ["derive"] }
rand = { version = "0.8.5", features = [ "small_rng" ] }
rand_distr="0.4.3"
nalgebra = "0.31.1"

# ---------- Logging
log = "0.4.0"
env_logger = "0.9.0"

[[bin]]
name = "polymer"
path = "src/polymer.rs"

[[bin]]
name = "disks"
path = "src/disks.rs"

[[bin]]
name = "argon"
path = "src/argon.rs"

[package.metadata.docs.rs]
# To build locally use
#   RUSTDOCFLAGS="--html-in-header katex-header.html" cargo doc --no-deps --document-private-items --open
rustdoc-args = ["--html-in-header", "katex-header.html"]
