
[package]
name = "bioshell-numerical"
version = "4.0.0-dev"
edition = "2021"
description = "Provides core functionality for BioShell package"
homepage = "https://bioshell.pl"
license = "Apache-2.0"
keywords = ["bioshell"]

[lib]
crate-type =["rlib"]

