
#[cfg(test)]
mod tests {
    use bioshell_seq::sequence::{bucket_clustering, FastaIterator, Sequence};

    const FDX_FASTA: &str = ">2Fe-2SST1(rhl:LPU83_2264)Rhizobium favelukesii
MPKLTIVAFDGTRFDLDVDQGSTVMENAVRNSVPGIEAECGGACACATCHVYVDDEWTER
VGPPEAMEEDMLDFAFDVRPTSRLSCQIRMKAALDGLTVHVPERQA
>2Fe-2SST1(mlo:msl0793)Mesorhizobium japonicum MAFF 303099
MTKLTFIAHDGTQFDVDAENGSTVMENAIRNAVPGIEAECGGACACATCHVYVDEAWTAE
VGEPEAMEEDMLDFAYDVQPNSRLSCQIKVRDALDGLVVRVPERQG
>2Fe-2SST1(mln:A9174_21805)Mesorhizobium loti NZP2037
MTKLTFIAHDGTQFDVDAENGSTVMENAIRNAVPGIEAECGGACACATCHVYVDEAWTAE
VGEPEAMEEDMLDFAYDVQPNSRLSCQIKVRDALDGLVVRVPERQG
>2Fe-2SST1(mci:Mesci_4101)Mesorhizobium ciceri (biovar Biserrulae)
MTKLTFIAHDGTHFDMDAENGSTVMENAIRNAVPGIEAECGGACACATCHVYVDEAWTAE
VGEPEAMEEDMLDFAYDVQPNSRLSCQIKVRDALDGLVVRVPARQG
>2Fe-2SST1(mop:Mesop_4144)Mesorhizobium opportunistum
MTKLTFIAHDGTHFDVDAENGSTVMENAIRNAVPGIEAECGGACACATCHVYVDEAWTAE
VGEPEAMEEDMLDFAYEVQPNSRLSCQIKVRDALDGLVVRVPERQG
>2Fe-2SST1(mam:Mesau_03907)Mesorhizobium australicum
MTKLTFIAHDGTHFDVDAENGSTVMENAIRNAVPGIEAECGGACACATCHVYVDEAWTAE
VGEPEAMEEDMLDFAYDVQPNSRLSCQIKVRDALDGLIVRVPERQG
>2Fe-2SST1(mamo:A6B35_18150)Mesorhizobium amorphae
MTKLTFIAHDGTQFDVDAENGSTVMENAIRNAVPGIEAECGGACACATCHVYVDEAWTAE
VGEPEAMEEDMLDFAYEVQPNSRLSCQIKVRDALDGLVVRVPARQG
>2Fe-2SST1(meso:BSQ44_12710)Mesorhizobium sp. B7
MTKITYIAHDGSKFEVEAENGSTVMENAIRNAVPGIEAECGGACACATCHVYVDEAWSAA
VGEPEAMEEDMLDFAYDVRPTSRLSCQIRVSDELDGLVVQVPERQA
>2Fe-2SST1(mes:Meso_1410)Chelativorans sp. BNC1
MPRLKFIAFDGTEFDIQADNGSTLMQNAVRNGVPGIEAECGGACACATCHVYVDEAWAEI
VGPPEPMEEDMLDFAYDVRPTSRLSCQVRVREELDGLTVRIPERQG";

    #[test]
    fn test_fdx_buckets() {
        let fdx_sequences = FastaIterator::new(FDX_FASTA.as_bytes()).collect::<Vec<Sequence>>();
        let fdx_clusters = bucket_clustering(&fdx_sequences, 0.8);

        for (i, cluster) in fdx_clusters.iter().enumerate() {
            println!("Cluster {}:", i + 1);
            for seq in cluster {
                println!("  - {}", seq.id());
            }
        }
    }
}