use bioshell_seq::alignment::{AlignmentReporter, PrintAsPairwise};
use bioshell_seq::sequence::Sequence;

#[test]
fn report_pairwise() {
    let query = Sequence::from_str("query", "AL-IV");
    let template = Sequence::from_str("template", "ALRIV");
    let mut reporter = PrintAsPairwise::new(10, 10);
    reporter.report(&query, &template);
}

#[allow(non_upper_case_globals)]
static seq1: &str = "MLLLIISILVIYGVYIKLIKPGFYWQKRGIVHAKPWMAIVKVVCSSKSFFEIIIDSYNQFSDR----SYQFMTPSLFVRDLDLIKRITVKDFDHFTDRMNFISEKADPLMGLNLFNLGGEKWRDMRSTLSPAFTSAKMRAMYTLMQETAEHFVEYFLLDDNEVIELEMKNIFSRYTNDVIANCAFGIKCDSLNEKNNEFYTMGLNVTTPKPSNMVRGVAAAFFPKVFEVLKIKVFSTTVWDFFRKIVSETISYREKENIIRPDMIHLLMEAKKGRLRHEDEKTSENDTGFATVEESALGKSVGKMELTHDLITAQALVFFLAGFDTASTLLSFLTYELALNPDIQTKLQAEVDEAAKA---GVSYEEILKMKYLDQVVSEALRKYPGGFILVRQCVKDYKIEAERDYEKDIVVEKDCLVTIPISGIHRDPNYFPDPERFDPDRFSDENKEKIVSGSYMPFGSGPRNCIGSRFALLEAKVLIVSLMSRFDIVPVKRTTVPITLAKSVNLTVKDGFWLGFKNRN-R";
#[allow(non_upper_case_globals)]
static seq2: &str = "MLWVFISVLAAYYVYEKIYKPSLYWTKRGVFHSKPWVRFFKTFIRRKAIAETVKEAYDLYPDRRYFGSFQFLYPSLFLRDIDLIKKVTVKDFEHFPDHLLVFNNDNDPLTNSSLFALKGEKWKNMRATLSPAFTSSKMKSMFILMNEIAENYVKNLGRNEEKLKEIEMKDLFSKYTTDIIATCAFGIDVDSLENDQNDFFFMGKAITKTTILGALKAVCIGFFPKITGYFGLRVFPSKVTDFFSQTMKETIAYREKQNIVRPDMVHLLLEARRGNLKIED-KENVPETGFATVKESYGIKSSGKIEITDDLMTGQALIFFFAGFETGSTVMSFLSYELALNTEIQSKLQQEIDEAMQKCNDNITYEEILSLKYLDQVISETLRKYPPGFALNRQCTKNYKIEAKLEHENDLIVEKGCSIVIPVFAIHRDPQFFPEPDKFEPDRFSEENKGNILAGTYMPFGSGPRNCIASRFALLETKALMVQIFSKFEVYPIEKTSIPLKLAKTQMLGSADGFWLGLRKRNDK";

#[test]
fn test_pairwise_formatting() {
    let query = Sequence::from_str("6dec30bed051266058bc2b8734161869:9Y", seq1);
    let template = Sequence::from_str("d3abd81011d04ee1d64da8868344462c:9BN", seq2);
    let mut reporter = PrintAsPairwise::new(8, 80);

    reporter.report(&query, &template);
}