
[package]
name = "bioshell-clustering"
version = "4.0.0-dev"
edition = "2021"
description = "Clustering methods"
homepage = "https://bioshell.pl"
license = "Apache-2.0"
keywords = ["bioshell"]

[lib]
crate-type =["rlib", "cdylib"]

[dependencies]
rand = {version = "0.8.5", features = [ "small_rng" ]}
rand_distr="0.4.3"
nalgebra = "0.31.1"
clap = { version = "3.1.18", features = ["derive"] }

bioshell-statistics = { path = "../bioshell-statistics" }
<<<<<<< HEAD
bioshell-core = { path = "../bioshell-core" }
=======
bioshell-core = { path = "../bioshell-core" }

>>>>>>> 0e673e79d45364b22d8fe660b1f31394a9f5f427
